CREATE TABLE TUITAPI;
USE TUITAPI;

CREATE TABLE USERS (
    id_user VARCHAR(40) NOT NULL PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);